version: '3.7'
services:  
  #kibana container
  kibana:    
    container_name: kibana
    hostname: kibana
    image: kibana:6.4.2
    ports:
      - 5601:5601
    volumes:
      - type: volume
        source: logs
        target: /var/log
    networks:
      - stacknet

  #Mysql container
  mysql:
    container_name: mqsql
    hostname: mysql
    build: ${PWD}/mysql/8.8
    environment:
      - "MYSQL_ROOT_PASSWORD=pass123"
    networks:
      - stacknet
    #Expose port 3306 to allow users to connect and perform operations.
    ports:
        - 3306:3306
    #Use named volume so mysql data is persisted across restart
    volumes:
      - type: volume
        source: /var/lib/mysql/
        target: mysqldata

  #Nginx container
  nginx:
    container_name: nginx
    hostname: nginx
    build: ${PWD}/stable/alpine
    networks:
      - stacknet
    #Expose port 80
    ports:
        - 8081:80
    command: /bin/bash -c "nginx -g 'daemon off;'"
    volumes:
      - type: volume
        source: /var/log/nginx/
        target: /var/log
        
  volumes:
  mysqldata:
    driver: local


  networks:
  stacknet:
    driver: bridge

